const productsData = [
    {
      id: 1,
      name: "Tecno Camon 19",
      //imageURL: "p1",
      price: "280",
      regularPrice:"350",
      category: "Phone",
      brand: "Tecno",
      desc: "The Tecno Camon 19 is a smartphone that effortlessly blends style and functionality to cater to the diverse needs of today's mobile users. Its standout feature is the advanced triple-lens camera system, capturing moments with exceptional clarity and detail. Whether you're a photography enthusiast or someone who enjoys spontaneous snapshots, the Camon 19 ensures your photos shine.Featuring a sleek and slim design, the Camon 19 boasts a 6.5-inch Full HD+ display that delivers vibrant visuals. The device is not just aesthetically pleasing but also comfortable to handle. Powered by a robust processor, it provides seamless multitasking and efficient performance. With ample storage and expandable memory options, you can store a plethora of content without worrying about space constraints.",
    },
    {
      id: 2,
      name: "Tecno spark 9, 4GB 64GB Memory - Black",
      //imageURL: "p2",
      price: "300",
      regularPrice:"450",
      category: "Phone",
      brand: "Tecno",
      desc: "The Tecno Camon 19 is a smartphone that effortlessly blends style and functionality to cater to the diverse needs of today's mobile users. Its standout feature is the advanced triple-lens camera system, capturing moments with exceptional clarity and detail. Whether you're a photography enthusiast or someone who enjoys spontaneous snapshots, the Camon 19 ensures your photos shine.Featuring a sleek and slim design, the Camon 19 boasts a 6.5-inch Full HD+ display that delivers vibrant visuals. The device is not just aesthetically pleasing but also comfortable to handle. Powered by a robust processor, it provides seamless multitasking and efficient performance.",
    },
    {
      id: 3,
      name: "Tecno Spark 9t (KH6) 6.6 HD",
      //imageURL: "p3",
      price: "300",
      regularPrice:"450",
      category: "Phone",
      brand: "Tecno",
      desc: "The Tecno Spark 9T (KH6) 6.6 HD is a feature-packed smartphone that redefines affordability without compromising on performance. With its expansive 6.6-inch HD display, immerse yourself in vivid visuals and enjoy a cinematic viewing experience for gaming, streaming, and browsing.Capture your memories in stunning detail with the Spark 9T's advanced AI dual-camera system. The main lens, combined with intelligent AI enhancements, ensures that your photos are vibrant and clear, while the secondary depth sensor adds a professional touch to your portraits. Whether it's a scenic landscape or a selfie with friends, the Spark 9T delivers impressive image quality. Under the hood, the Tecno Spark 9T is powered by a reliable processor, providing smooth multitasking and efficient performance.",
    },
    {
      id: 4,
      name: "Samsung Galaxy S8 5.8-inch",
      //imageURL: "p4",
      price: "400",
      regularPrice:"580",
      category: "Phone",
      brand: "Samsung",
      desc: "The Samsung Galaxy S8, with its stunning 5.8-inch display, is a flagship smartphone that seamlessly blends elegance with cutting-edge technology. Immerse yourself in a visual feast as the Quad HD+ Super AMOLED screen delivers vibrant colors, sharp contrasts, and crisp details, ensuring a captivating viewing experience for photos, videos, and applications.Equipped with a high-resolution 12MP rear camera and an 8MP front-facing camera, the Galaxy S8 empowers you to capture life's moments with exceptional clarity and precision. The advanced camera features, including fast autofocus and low-light optimization, make every photo a masterpiece. The 5.8-inch form factor ensures a comfortable grip while still providing a generous canvas for creativity. Underneath its sleek exterior, the Galaxy S8 boasts powerful performance driven by a cutting-edge processor. The phone is designed to handle multitasking seamlessly, ensuring smooth transitions between apps and a responsive user experience.",
    },
    {
      id: 5,
      name: "Samsung Galaxy S9 Plus S9+",
      //imageURL: "p5",
      price: "400",
      regularPrice:"650",
      category: "Phone",
      brand: "Samsung",
      desc: "The Samsung Galaxy S9, with its stunning 5.8-inch display, is a flagship smartphone that seamlessly blends elegance with cutting-edge technology. Immerse yourself in a visual feast as the Quad HD+ Super AMOLED screen delivers vibrant colors, sharp contrasts, and crisp details, ensuring a captivating viewing experience for photos, videos, and applications. Equipped with a high-resolution 12MP rear camera and an 8MP front-facing camera, the Galaxy S8 empowers you to capture life's moments with exceptional clarity and precision. The advanced camera features, including fast autofocus and low-light optimization, make every photo a masterpiece. The 5.8-inch form factor ensures a comfortable grip while still providing a generous canvas for creativity. Underneath its sleek exterior, the Galaxy S8 boasts powerful performance driven by a cutting-edge processor. The phone is designed to handle multitasking seamlessly, ensuring smooth transitions between apps and a responsive user experience.",
    },
    {
      id: 6,
      name: "Polystar 40 Inches Android Smart Curved TV",
      //imageURL: "p6",
      price: "900",
      regularPrice:"1500",
      category: "Electonics",
      brand: "Polystar",
      desc: "Introducing the Polystar 40 Inches Android Smart Curved TV, where immersive entertainment meets intelligent technology. This sleek and sophisticated television not only enhances your viewing experience but also brings the power of Android to your living room. Immerse yourself in stunning visuals with the 40-inch curved display, designed to provide a panoramic and lifelike viewing experience. The curvature adds depth to your content, pulling you into the heart of the action, whether you're watching movies, gaming, or streaming your favorite shows. Powered by Android, this smart TV opens up a world of possibilities. Access a vast array of apps, games, and content through the Google Play Store, all from the comfort of your couch. The intuitive interface makes navigation a breeze, and the TV's processing power ensures seamless performance for a truly connected experience.",
    },
    {
      id: 7,
      name: "Infinity 32 INCHES SMART FULL HD LED TV",
      //imageURL: "p7",
      price: "1000",
      regularPrice:"1500",
      category: "Electronics",
      brand: "Infinity",
      desc: "Introducing the Infinity 32 Inches Smart Full HD LED TV, a perfect fusion of technology and entertainment designed to redefine your viewing experience. This television is not just a display; it's a gateway to a world of captivating visuals and smart connectivity. The 32-inch Full HD LED screen ensures crystal-clear images with vibrant colors and sharp contrasts, making every scene come to life. Whether you're watching your favorite movies, sports, or streaming content, the Infinity Smart TV delivers a visually immersive experience. With smart functionality, this TV opens up a realm of possibilities. Built-in Wi-Fi connectivity allows you to seamlessly access a variety of streaming services and apps, transforming your TV into an entertainment hub. Enjoy the convenience of on-demand content, from the latest shows to trending movies, right at your fingertips. Navigating through the TV's features is a breeze thanks to the user-friendly interface. Connect effortlessly with multiple HDMI and USB ports, providing flexibility for external devices such as gaming consoles, Blu-ray players, or USB drives. The Infinity Smart TV adapts to your lifestyle, offering both convenience and versatility.",
    },
    {
      id: 8,
      name: "Edifier Bluetooth Speakers",
      //imageURL: "p8",
      price: "800",
      regularPrice:"1000",
      category: "Gadget",
      brand: "Edifier",
      desc: "Introducing the Edifier Bluetooth Speakers, where cutting-edge audio technology meets sleek design for an unparalleled listening experience. Elevate your sound and style with these wireless speakers that redefine what premium audio means. Immerse yourself in rich, high-fidelity sound delivered by state-of-the-art drivers and advanced Bluetooth technology. The Edifier speakers provide a room-filling audio experience, whether you're streaming music, watching movies, or gaming. With a perfect balance of crisp highs and deep lows, every note is rendered with precision, making your favorite tunes come alive.The Bluetooth connectivity of these speakers ensures a hassle-free setup, allowing you to connect wirelessly to your devices with ease. Say goodbye to the limitations of cables and enjoy the freedom to control your audio experience from any corner of the room. Crafted with an eye for aesthetics, the Edifier Bluetooth Speakers seamlessly blend into your living space.",
    },
    {
      id: 9,
      name: "Djack 3.1 Max Sound Bluetooth Home Theatre",
      //imageURL: "p9",
      price: "1500",
      regularPrice:"2000",
      category: "Electronics",
      brand: "Djack",
      desc: "Introducing the Edifier Bluetooth Speakers, where cutting-edge audio technology meets sleek design for an unparalleled listening experience. Elevate your sound and style with these wireless speakers that redefine what premium audio means. Immerse yourself in rich, high-fidelity sound delivered by state-of-the-art drivers and advanced Bluetooth technology. The Edifier speakers provide a room-filling audio experience, whether you're streaming music, watching movies, or gaming. With a perfect balance of crisp highs and deep lows, every note is rendered with precision, making your favorite tunes come alive.The Bluetooth connectivity of these speakers ensures a hassle-free setup, allowing you to connect wirelessly to your devices with ease. Say goodbye to the limitations of cables and enjoy the freedom to control your audio experience from any corner of the room. Crafted with an eye for aesthetics, the Edifier Bluetooth Speakers seamlessly blend into your living space. The sleek and modern design, coupled with premium materials, not only enhances the visual appeal of your setup but also complements the sophistication of your lifestyle. Designed for convenience, these speakers feature intuitive controls, allowing you to adjust volume, playback, and settings effortlessly.",
    },
    {
      id: 10,
      name: "Hp Pavilion 15 Intel Core I5",
      //imageURL: "p10",
      price: "2000",
      regularPrice:"2500",
      category: "Laptop",
      brand: "Hp",
      desc: "Introducing the HP Pavilion 15 with Intel Core i5 – a powerhouse of performance and versatility in a sleek and sophisticated design. Engineered for productivity and entertainment, this laptop takes your computing experience to new heights, whether you're working, creating, or enjoying multimedia content. At its core, the Intel Core i5 processor ensures seamless multitasking and responsive performance. Tackle demanding applications, run multiple programs simultaneously, and experience faster load times, all while enjoying the efficiency and power of Intel's cutting-edge technology. The Pavilion 15 boasts a stunning 15.6-inch display that brings your visuals to life with vibrant colors and sharp details. Whether you're editing photos, streaming videos, or working on spreadsheets, the Full HD resolution provides a visually immersive experience. Designed with user convenience in mind, the HP Pavilion 15 combines functionality with style. The slim profile and sleek finish make it a portable companion, while the backlit keyboard adds a touch of sophistication.",
    },
    {
      id: 11,
      name: "Hp Stream 11 Intel Celeron Quad Core",
      //imageURL: "p11",
      price: "2000",
      regularPrice:"2500",
      category: "Laptop",
      brand: "Hp",
      desc: "Introducing the HP Stream 11 powered by Intel Celeron Quad Core – a compact and vibrant laptop designed for users on the move. Packed with features to enhance your daily tasks, this ultraportable device delivers reliable performance and connectivity in a stylish, lightweight package. The Intel Celeron Quad Core processor ensures smooth and efficient operation, making multitasking a breeze. Whether you're browsing the web, streaming content, or working on documents, the HP Stream 11 handles it all with ease, providing a responsive computing experience. The 11.6-inch HD display offers crisp visuals and vibrant colors, making it ideal for both work and play. The compact size and lightweight design make the Stream 11 a perfect companion for those who are always on the go. Slip it into your bag, and you're ready to take your digital world with you wherever you venture. The laptop comes pre-installed with Windows 10, offering a familiar and user-friendly interface.",
    },
    {
      id: 12,
      name: "Apple Macbook Air 13.3 8GB25GB",
      //imageURL: "p12",
      price: "3000",
      regularPrice:"3500",
      category: "Laptop",
      brand: "Apple",
      desc: "Introducing the Apple MacBook Air 13.3 with 8GB RAM and 256GB SSD – a sleek and powerful laptop that epitomizes innovation and performance. Immerse yourself in the seamless integration of cutting-edge technology and elegant design, delivering an unparalleled computing experience.The MacBook Air's 13.3-inch Retina display sets a new standard for visual excellence, with True Tone technology that adapts to ambient lighting, providing vibrant colors and sharp details. Whether you're editing photos, watching videos, or working on creative projects, the stunning Retina display ensures a visual feast. Powered by an Intel processor, the MacBook Air offers responsive and efficient performance. The 8GB RAM ensures smooth multitasking, allowing you to effortlessly switch between applications, while the 256GB SSD provides lightning-fast data access and ample storage space for your files and applications. Crafted from a single piece of aluminum, the MacBook Air's lightweight and slim design make it a portable powerhouse. ",
    },
    {
      id: 13,
      name: "Sony Playstation 5",
      //imageURL: "p13",
      price: "800",
      regularPrice:"1000",
      category: "Game",
      brand: "Sony",
      desc: "Introducing the Sony PlayStation 5 – a gaming console that redefines the future of immersive gaming experiences. Unleash the power of cutting-edge technology and innovative design, transporting you to new realms of entertainment and excitement. The PlayStation 5 boasts a revolutionary DualSense wireless controller, designed to provide haptic feedback and adaptive triggers that respond to in-game actions with astonishing precision. Feel the tension of your bowstring or the impact of every explosion as you dive into a level of sensory immersion that was previously unmatched. With a custom-designed AMD processor and high-speed SSD, the PS5 delivers lightning-fast loading times and stunning graphics. Enjoy games in 4K resolution at 120Hz, with ray tracing technology that brings lifelike lighting and reflections to your screen, creating an unparalleled visual feast. Immerse yourself in a vast library of games, including exclusive titles that showcase the full potential of the PlayStation 5. From action-packed adventures to visually stunning worlds, the PS5 offers a gaming experience that transcends boundaries. The sleek and futuristic design of the console is not just visually striking but also optimized for efficient cooling, ensuring a quiet and reliable performance. The user-friendly interface provides easy access to your favorite games, streaming services, and social features.",
    },
  ];